Repository BranDebs/Avocado-Frontend, pull requests merged in 2019-07, with the labels that each got.

#18 By add home mockup
  README.old.md
  package-lock.json
  src/App.js
  src/components/About.js
  src/components/Home.js
  src/components/avocadoro/task/Completed.js
  src/components/avocadoro/task/InProgress.js
  src/components/avocadoro/task/Task.js
  src/components/avocadoro/task/TaskCard.js
  src/components/avocadoro/task/TaskList.js
  src/components/avocadoro/timer/Selections.js
  src/components/avocadoro/timer/Settings.js
  src/components/avocadoro/timer/Timer.js
Labels: PR Size: Medium, Type: Enhancement

#20 Add timer countdown for avocadoro and long/short breaks
  src/components/avocadoro/timer/Selections.js
  src/components/avocadoro/timer/Timer.js
Labels: Prioriy: Medium, Type: Enhancement

#21 UI Design for Navbar and Timer
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Home.js
  src/components/avocadoro/timer/Selections.js
  src/components/avocadoro/timer/Timer.css
  src/components/avocadoro/timer/Timer.js
  src/components/layout/Navbar.css
  src/components/layout/Navbar.js
  src/components/layout/SignedInLink.js
  src/components/layout/SignedOutLink.js
  src/images/Avocadoro-icon.png
Labels: PR Size: Medium, Type: Enhancement

#22 Add start, pause and reset timer buttons
  src/components/avocadoro/timer/Controls.js
  src/components/avocadoro/timer/Selections.js
  src/components/avocadoro/timer/Timer.js
Labels: PR Size: Small, Type: Enhancement

#23 Add raw Balsamiq mockups of Avocadoro Design
  src/docs/Logged_In_home_page.png
  src/docs/Logged_In_home_page1.png
  src/docs/Login_Page.png
  src/docs/Main_Page.png
  src/docs/Settings.png
  src/docs/Signup_page.png
Labels: PR Size: Small

#30 Fix timer inaccuracy due to unfocusing of the tab
  src/components/avocadoro/timer/Timer.js
Labels: PR Size: Small, Priority: Medium, Status: Awaiting Review

#31 UI Fixes and Additions
  public/index.html
  src/App.js
  src/components/Home.js
  src/components/avocadoro/timer/Controls.js
  src/components/avocadoro/timer/Selections.js
  src/components/avocadoro/timer/Settings.js
  src/components/avocadoro/timer/Timer.css
  src/components/avocadoro/timer/Timer.js
  src/components/layout/Navbar.css
  src/components/layout/Navbar.js
  src/images/Avocadoro-icon.png
  src/images/Avocadoro-icon1.png
Labels: PR Size: Medium, Type: Enhancement
