Repository BranDebs/Avocado-Frontend, pull requests merged in 2020-01, with the labels that each got.

#43 Refactor swap to materialui
  CONTRIBUTING.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/about/About.js
  src/components/auth/SignIn.js
  src/components/auth/SignInForm.js
  src/components/auth/SignUpForm.js
  src/components/auth/auth.css
  src/components/dashboard/Home.js
  src/components/dashboard/timer/Controls.js
  src/components/dashboard/timer/Selections.js
  src/components/dashboard/timer/SettingsModal.js
  src/components/dashboard/timer/Timer.css
  src/components/dashboard/timer/Timer.js
  src/components/dashboard/todo/Completed.js
  src/components/dashboard/todo/InProgress.js
  src/components/dashboard/todo/TodoCard.js
  src/components/dashboard/todo/TodoList.js
  src/components/navigation/Navbar.js
  src/components/navigation/SignedInLink.js
  src/components/navigation/SignedOutLink.js
  src/server/validations/ValidateLogin.js
Labels: PR Size: Medium, Priority: High

#46 Feat redux skeleton
  package-lock.json
  package.json
  src/components/auth/SignInForm.js
  src/components/dashboard/timer/SettingsModal.js
  src/components/dashboard/todo/TodoCard.js
  src/components/navigation/SignedInLink.js
  src/index.js
  src/redux/actions/actionType.js
  src/redux/configureStore.js
  src/redux/reducers/index.js
  src/server/validations/ValidateLogin.js
Labels: PR Size: Medium, Priority: Medium, Type: Enhancement

#47 Feat settings modal
  package-lock.json
  package.json
  src/components/dashboard/Home.js
  src/components/navigation/Navbar.js
  src/components/navigation/SignedInLink.js
  src/components/settings/Settings.js
  src/components/settings/SettingsModal.js
  src/containers/Settings.js
  src/containers/SignedInLink.js
  src/redux/actions/actionType.js
  src/redux/actions/actionTypes.js
  src/redux/actions/settings.js
  src/redux/reducers/index.js
  src/redux/reducers/settings.js
Labels: PR Size: Medium, Priority: Medium, Type: Enhancement

#49 ci(github-actions): add PR labeler
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: PR Size: Small, Priority: Medium, ci

#48 docs(readme): update readme
  CONTRIBUTING.md
  README.md
Labels: Priority: Medium

#50 ci(github-actions): add size labeler
  .github/workflows/size-label.yml
Labels: ci, size/S

#45 ui(web icon): add avocado svg icon
  src/components/auth/SignInForm.js
  src/components/dashboard/timer/Selections.js
  src/components/dashboard/timer/SettingsModal.js
  src/components/dashboard/timer/Timer.js
  src/components/navigation/Navbar.js
  src/const/TimerConst.js
  src/const/UiConst.js
  src/images/Avocadoro-icon.svg
  src/images/Avocadoro-icon1.png
Labels: Priority: Low, feature

#52 fix(pathing): fix constant file path
  src/components/dashboard/timer/Selections.js
  src/components/dashboard/timer/Timer.js
  src/components/navigation/Navbar.js
Labels: fix, size/XS

#53 fix(todolist): add unique key for component
  src/components/dashboard/todo/Todo.js
  src/components/dashboard/todo/TodoList.js
  src/containers/TodoList.js
  src/redux/actions/actionTypes.js
  src/redux/actions/todoList.js
  src/redux/reducers/index.js
  src/redux/reducers/todoList.js
Labels: feature, size/M

#54 ui(card): update card ui element
  src/components/dashboard/todo/Todo.css
  src/components/dashboard/todo/TodoCard.js
  src/components/navigation/Navbar.js
  src/const/UiConst.js
Labels: size/M

#56 refactor(stylng): follow prettier format
  src/components/dashboard/todo/Completed.js
  src/components/dashboard/todo/InProgress.js
  src/components/dashboard/todo/TaskCard.js
  src/components/dashboard/todo/Todo.js
  src/components/dashboard/todo/TodoList.js
  src/const/Task.js
  src/containers/Completed.js
  src/containers/InProgress.js
  src/containers/TodoList.js
  src/redux/actions/actionTypes.js
  src/redux/actions/taskCard.js
  src/redux/actions/todoList.js
  src/redux/reducers/completedList.js
  src/redux/reducers/inProgressList.js
  src/redux/reducers/index.js
  src/redux/reducers/todoList.js
  src/utils/taskUtil.js
Labels: feature, size/L

#58 feat(start todo): add starting of todo
  src/components/dashboard/todo/TaskCard.js
  src/components/dashboard/todo/TodoList.js
  src/containers/TodoList.js
  src/redux/actions/actionTypes.js
  src/redux/actions/inProgress.js
  src/redux/actions/todoList.js
  src/redux/reducers/inProgressList.js
  src/redux/reducers/todoList.js
Labels: feature, size/M

#57 feat(settings modal): update ui for settings modal
  src/components/dashboard/Home.js
  src/components/dashboard/timer/SettingsModal.js
  src/components/dashboard/timer/Timer.js
  src/components/settings/Settings.js
  src/components/settings/SettingsModal.js
Labels: feature, size/L

#59 fix(timer util): fix
  src/utils/timerUtil.js
Labels: fix, size/S

#60 feat(finish task): add finish in progress task
  src/components/dashboard/todo/Completed.js
  src/components/dashboard/todo/InProgress.js
  src/containers/InProgress.js
  src/redux/actions/actionTypes.js
  src/redux/actions/completed.js
  src/redux/actions/inProgress.js
  src/redux/reducers/completedList.js
  src/redux/reducers/inProgressList.js
Labels: feature, size/M

#62 feat(completed_task): hook up archive handler to archive button
  src/components/dashboard/todo/Completed.js
  src/components/dashboard/todo/InProgress.js
  src/components/dashboard/todo/TaskCard.js
  src/components/dashboard/todo/TodoList.js
  src/containers/Completed.js
  src/containers/InProgress.js
  src/containers/TodoList.js
  src/redux/actions/actionTypes.js
  src/redux/actions/completed.js
  src/redux/actions/inProgress.js
  src/redux/actions/taskCard.js
  src/redux/actions/todoList.js
  src/redux/reducers/completedList.js
  src/redux/reducers/inProgressList.js
  src/redux/reducers/todoList.js
Labels: feature, size/L

#61 feat--signup page
  src/components/auth/SignInForm.js
  src/components/auth/SignUpForm.js
Labels: feature, size/L

#64 feat(howlerjs): add in alarm sound when timer is up
  package-lock.json
  package.json
  src/components/dashboard/timer/Timer.js
  src/sounds/avocadoro_alarm_1.mp3
  src/sounds/avocadoro_alarm_2.mp3
  src/utils/audio.js
Labels: feature, size/M

#63 feat(card): update card ui and add favicon, fix timer tabs
  public/favicon.ico
  src/components/auth/SignUpForm.js
  src/components/dashboard/timer/Selections.js
  src/components/dashboard/timer/Timer.js
  src/components/dashboard/todo/TaskCard.js
  src/components/dashboard/todo/TodoList.js
  src/components/settings/Settings.js
  src/const/Font.js
  src/const/Timer.js
Labels: feature, size/L

#66 feat(settings): add settings feature
  src/components/dashboard/Home.js
  src/components/settings/Settings.js
  src/components/settings/SettingsModal.js
  src/containers/SettingsModal.js
  src/redux/actions/actionTypes.js
  src/redux/actions/settings.js
  src/redux/reducers/settings.js
Labels: feature, size/M

#67 feat(timer-settings): integrate settings into timer
  src/components/dashboard/Home.js
  src/components/dashboard/timer/Selections.js
  src/components/dashboard/timer/Timer.js
  src/components/settings/Settings.js
  src/containers/Timer.js
  src/redux/reducers/settings.js
  src/utils/timerUtil.js
Labels: size/M
