Repository BranDebs/Avocado-Frontend, pull requests merged in 2020-03, with the labels that each got.

#70 feat(card): Colour change on card hover
  package.json
  src/components/Navbar/index.jsx
  src/components/TaskCard/index.jsx
  src/components/TaskList/index.jsx
  src/components/TaskTracker/index.jsx
Labels: feature, size/L

#71 feat(TaskCard): add editing mode state
  src/components/TaskCard/index.jsx
  src/components/TaskList/index.jsx
  src/containers/TaskCard.js
  src/containers/TaskTracker.js
  src/redux/actions/actionTypes.js
  src/redux/actions/tasks.js
  src/redux/reducers/tasks.js
Labels: feature, size/M

#72 docs(readme): update readme and contributing
  CONTRIBUTING.md
  README.md
Labels: docs, size/S

#73 feat(Timer): add avocombo
  src/components/TaskCard/index.jsx
  src/components/TaskList/index.jsx
  src/components/Timer/Selections.js
  src/components/Timer/index.jsx
  src/components/Timer/timer.js
  src/const/timer.js
  src/containers/Timer.js
Labels: feature, size/L

#75 refactor(components): base on eslint
  src/components/TaskCard/index.jsx
  src/components/Timer/index.jsx
  src/components/dashboard/Home.css
  src/components/dashboard/Home.js
  src/components/dashboard/todo/Completed.js
  src/components/dashboard/todo/InProgress.js
  src/components/dashboard/todo/Todo.js
  src/components/navigation/Navbar.js
  src/pages/SignIn.js
  src/pages/SignUp.js
  src/utils/audio.js
Labels: refactor, size/L

#76 Fix navbar
  src/components/Navbar/index.jsx
  src/components/TaskCard/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/reducers/auth.js
Labels: fix, size/M
